### ISSUE TITLE
Notification theme is the same for both Light and Dark Theme

### ISSUE THREAD

**Issue by m4u9** [shimmerproject/Greybird-Geeko#8]
Greybird-Geeko-Dark should be using a dark theme instead of bright theme

![Screenshot_2019-07-16_22-03-01](https://user-images.githubusercontent.com/44322817/61300985-9dfe9e80-a815-11e9-9938-3e4d46c13f28.png)

**Comment by sowelipililimute** [comment]
Fixed in commit 1a7574f241b6233d44c135a079cda89b80d2eed6
